{% set name = "adb-shell" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/adb_shell-{{ version }}.tar.gz
  sha256: 04c305f30a2ca25d5c54b3cd6ce9bb64c36e5f07967b23b3fb6aaecc851b90b6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cryptography
    - pyasn1
    - python >={{ python_min }}
    - rsa

test:
  imports:
    - adb_shell
    - adb_shell.auth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/JeffLIrion/adb_shell
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Python implementation of ADB with shell and FileSync functionality.
  description: |
    This Python package implements ADB shell and FileSync functionality. 
    It originated from python-adb.
  doc_url: https://adb-shell.readthedocs.io/
  dev_url: https://github.com/JeffLIrion/adb_shell

extra:
  recipe-maintainers:
    - jan-janssen
